version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    image: apolos7/api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - msvc
    restart: always

networks:
  msvc:
    name: msvc